on: [push, pull_request]

name: Unit Tests
jobs:

  linux:
    name: Linux Dockers
    runs-on: ubuntu-latest
    strategy:
        matrix:
            dockerfile: [Dockerfile.ubuntu.bionic, Dockerfile.ubuntu.focal, Dockerfile.debian, Dockerfile.fedora, Dockerfile.kali, Dockerfile.parrot]

    steps:
        - name: Build test images
          uses: docker/build-push-action@v2.6.1
          with:
            file: Dockerfile.ubuntu.bionic
            
